service: serverless-prueba

provider: 
  name: aws
  runtime: nodejs14.12.0

functions: 
  info:
    handler: Handler/handler.info
    events:
      - http:
          path: path-de-info
          method: get
          cors: true
  guardar:
      handler: Handler/handler.guardar
      events:
        - http:
            path: path-de-guardar
            method: post
            cors: true